= 스타트업 컴포넌트 구성
:sectnums:
:toc:

== Back-End
=== 개발환경 구성하기
각 서비스(컴포넌트)는 독립적인 서비스를 제공한다.

=== Jira software
프로젝트 일정 관리
```
docker run --name jira_software --detach --mount source=JIRA_HOME,destination=/var/atlassian/jira \
--publish 8080:8080 cptactionhank/atlassian-jira
```

=== Gitlab
소스코드 형상 관리

==== Gitlab 설치 
https://docs.gitlab.com/omnibus/docker/#pre-configure-docker-container

* hostname
* external_url
* gitlab_rails['gitlab_shell_ssh_port']는 ssh port와 동일하게 설정
* ports (extneral : container port)

```
gitlab:
  image: 'gitlab/gitlab-ce:latest'
  restart: always
  hostname: '192.168.0.12'
  environment:
    GITLAB_OMNIBUS_CONFIG: |
      external_url 'http://192.168.0.12'
      gitlab_rails['gitlab_shell_ssh_port'] = 10022
      # Add any other gitlab.rb configuration here, each on its own line
  ports:
    - '10080:80'
    - '10443:443'
    - '10022:22'
  volumes:
    - 'GITLAB_CONFIG:/etc/gitlab'
    - 'GITLAB_LOG:/var/log/gitlab'
    - 'GITLAB_DATA:/var/opt/gitlab'
```

==== Jira Integration
* https://docs.gitlab.com/ee/user/project/integrations/jira.html

==== Slack Integration
- Integration에서 활성화. 매우 간단

=== Spec
==== Spock
==== Cucumber
==== Selenium

=== Containerized Spring Boot App

=== Monitoring
==== Grafana, Superset
==== InfluxDb
=== MongoDb
=== ElasticSearch, Kibana
로그 수집 및 조회 

=== Fluentd, Filebeat
로그 수집 에이전트

=== Nexus maven repository
라이브러리를 재활용하기 위해 필요

=== Redis
세션 관리

=== Sentry
에러 로그 알림
- https://github.com/getsentry/onpremise
- https://docs.sentry.io/clients/java/modules/logback/

=== 인증서 
- Let's encrypt

== Front-End
=== Vue
=== Bootstrap

== 기타 
=== Spark, Druid, ES
=== Intellij 설정
==== Lombok 설정
* Install the **Lombok plugin**
* **Enable Annotation Processing** see documentation
* Install the Latest Maven on your system and configure IntelliJ to use it (as opposed to the bundled one) see documentation


== 서버 구성 
- Conoha reverse proxy 
- 노트북 (i3, 8GB, 80G)

